### ISSUE TITLE
DefaultBodyReadables readableAsString doesn't retain UTF-8 Encoding

### ISSUE THREAD

**Issue by Eichhrn** [playframework/play-ws#187]
Hello,

I currently utilize an AhcWSClient for testing our REST API. After switching from play-ws 2.5.4 to play-ahc-ws-standalone 1.0.4 I noticed that my WSResponses from the GET/POST calls didn't retain their UTF-8 encoding. I used JsonBodyWritables for the get/post calls and DefaultBodyReadables for the following call:

```scala
def get(path: String, headers: (String, String)*)(implicit timeout: Timeout): (Int, String) = {
    val response = Await.result(wsClient.url(s"$baseURL$path").withHttpHeaders(("Content-Type" → applicationJson) +: headers: _*).get(), timeout.duration)
    (response.status, response.body[String])
  }
```

When comparing the resulting response.body[String] with my expected values I noticed that special characters weren't displayed correctly and caused the tests to fail, e.g. 'ß'.

As a workaround I used the following implicit reader instead of the DefaultBodyReadables, now my tests pass:

```scala
implicit val readableAsString: BodyReadable[String] = BodyReadable(_.bodyAsBytes.decodeString("UTF-8"))
```

Is there a misunderstanding on my part, or does this hint at a possible bug? I never had to bother with this in Play-WS 2.5.4, there I could just do result.body and got the correctly formatted output.

**Comment by djx314** [comment]
+1
I use a wsclient to post the file to an other play application and the code is:
```scala
ws.url(hentaiConfig.encoderUrl)
      .post(
      Source(
        FilePart("video_0", new String(sourceFile.getFileName.toString.getBytes(Charset.forName("utf-8")), Charset.defaultCharset), Option("""text/plain; charset=UTF-8"""), FileIO.fromPath(sourceFile)) ::
          DataPart("videoKey", key) :: Nil))
```

And if I use
```scala
FilePart("video_0", sourceFile.getFileName.toString, Charset.defaultCharset), Option("""text/plain; charset=UTF-8"""), FileIO.fromPath(sourceFile))
```
the server will receive the file name with messy code.

@wsargent  Any fix?

**Comment by gmethvin** [comment]
The root cause of the behavior you're seeing is actually in AsyncHttpClient, as we're delegating to its logic for obtaining a string representation of the body. The logic it uses is very simple: it checks for a `charset` parameter on the `Content-Type`; if that's not there, it defaults to `iso-8859-1`.

The larger problem here is that every MIME type can declare its own rules for encodings, and some don't even have a reasonable textual representation. So at best a `body: String` method can provide a guess at what the actual textual representation is.

In the case of `application/json`, if we want to fully implement RFC7159, it's not good enough to parse as UTF-8; it's also necessary to detect and support [other Unicode encodings](https://tools.ietf.org/html/rfc4627#section-3). A similar situation exists for `application/xml`, since the encoding may be specified in the XML declaration. In such cases we need custom logic that actually read the body to know how to properly interpret it as a string.

My suggestion here would be to pick a simple algorithm for detecting the encoding and clearly document it. We should warn that this is only attempts to "guess" the encoding of the body, and it's best to use the `BodyReadable` specific to that Content-Type if you can.

**Comment by djx314** [comment]
Great!
