### ISSUE TITLE
Add the full name for the abbreviation WS to the documentation

### ISSUE THREAD

**Issue by YourPsychiatrist** [playframework/play-ws#382]
I feel pretty stupid but I don't know whether WS stands for WebService or for WebSocket or something completely different. Seems like a no-brainer to me to explain the name in the documentation but I can't seem to find it. Would you mind adding it or just commenting it on the issue and then closing it?

**Comment by marcospereira** [comment]
WebService. :-)

If you want to add this to the docs, here is where it should be done:

- https://github.com/playframework/playframework/blob/master/documentation/manual/working/javaGuide/main/ws/JavaWS.md
- https://github.com/playframework/playframework/blob/master/documentation/manual/working/scalaGuide/main/ws/ScalaWS.md

Possibly a good idea to add some information for javadocs and scaladocs as well:

- https://github.com/playframework/playframework/blob/master/transport/client/play-ws/src/main/java/play/libs/ws/WSClient.java
- https://github.com/playframework/playframework/blob/master/transport/client/play-ws/src/main/scala/play/api/libs/ws/WSClient.scala

Let me know if you want to work on that so that I can transfer the issue to /playframework/playframework repo too.

Thanks!

**Comment by YourPsychiatrist** [comment]
@marcospereira You are a national treasure ;) I'll just add the full name to the *WS.md files!

**Comment by YourPsychiatrist** [comment]
I just saw that that you are referring to the playframework repo but I am uncertain whether I should just commit my additional two words to the main branch of the whole play framework. :/

**Comment by marcospereira** [comment]
Hey @YourPsychiatrist,

You can [create a fork](https://help.github.com/en/articles/fork-a-repo) of the playframework/playframework repo and then [submit a pull request](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork). This will be the best way since you are changing multiple files.

Best.

**Comment by YourPsychiatrist** [comment]
I figured I would have to do it that way but I wasn't sure whether there are any strict rules I have to abide by. Anyway, I'll just create a pull request referencing this issue; I hope that'll do :)

**Comment by renatocaval** [comment]
This was solved by #9544
