### ISSUE TITLE
shaded asynchttpclient sources are not published

### ISSUE THREAD

**Issue by domdorn** [playframework/play-ws#85]
shaded-asynchttpclient-1.0.0-M4-sources.jar is only 256 bytes big and contains only the manifest.mf file.

**Comment by wsargent** [comment]
fixed

**Comment by wsargent** [comment]
Okay, not fixed, but the sources is org.asynchttpclient

**Comment by domdorn** [comment]
hmm... yeah, problem is debugging issues related to plays ws client that way.. 

the underlying problem seems to be, that the shading happens on bytecode level... just noticed this when I tried to replace those constants
https://github.com/AsyncHttpClient/async-http-client/blob/1b35dbe96a25b253ac0381ce59b826a8831a7cb7/client/src/main/java/org/asynchttpclient/config/AsyncHttpClientConfigHelper.java#L33

I'll see if I find a adequate solution for that.

**Comment by jhooda** [comment]
The problem is when attaching debugger with a running process using any shaded library. The non-shaded source code won't bind with the shaded classes that belong to the shaded packages such as 

`
package play.shaded.ahc.io.netty.channel.nio;
...
public abstract class AbstractNioChannel extends AbstractChannel {
`
The source code is still 266 bytes, see, https://repo1.maven.org/maven2/com/typesafe/play/shaded-asynchttpclient/2.1.3/

So any plan to correctly publish shaded sources?

**Comment by mkurz** [comment]
@jhooda Please open a new issue for that, thanks!

**Comment by jhooda** [comment]
Thanks @mkurz filed the new issue https://github.com/playframework/play-ws/issues/683
